-- ============================================================
-- TRAQQ DATABASE — SCRIPT 6: WEBHOOK LOGS + INSIGHTS TABLES
-- ============================================================

-- ── WEBHOOK LOGS ─────────────────────────────────────────────
-- Every webhook from Korapay is logged here IMMEDIATELY on receipt,
-- before any processing happens. This is non-negotiable.
--
-- Why? Because:
-- 1. Korapay retries failed webhooks — we need deduplication
-- 2. If processing fails, we have the raw payload to retry
-- 3. Debugging payment issues without this is a nightmare
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS webhook_logs (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Korapay event type e.g. "charge.success", "charge.failed"
  event_type      text,

  -- Korapay's unique reference for this transaction
  -- Used for deduplication — if we've seen this ref, skip processing
  korapay_ref     text,

  -- Full raw payload from Korapay, stored as-is
  payload         jsonb NOT NULL,

  -- Processing lifecycle
  status          text NOT NULL DEFAULT 'received'
                  CHECK (status IN ('received', 'processed', 'failed', 'duplicate')),

  -- If processing failed, why?
  error_message   text,

  -- Signature verification result
  signature_valid boolean,

  received_at     timestamptz NOT NULL DEFAULT now(),
  processed_at    timestamptz
);

-- Deduplication: check if we've seen this korapay_ref before
CREATE INDEX IF NOT EXISTS idx_webhook_logs_korapay_ref
  ON webhook_logs(korapay_ref)
  WHERE korapay_ref IS NOT NULL;

-- Monitoring: find failed webhooks that need retry
CREATE INDEX IF NOT EXISTS idx_webhook_logs_status
  ON webhook_logs(status, received_at DESC);


-- ── INSIGHTS ─────────────────────────────────────────────────
-- Generated by the rule engine after each sale.
-- Stored so they persist between sessions and load instantly.
-- Vendors don't wait for computation — insights are pre-generated.
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS insights (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  vendor_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Which rule generated this insight
  insight_type    text NOT NULL
                  CHECK (insight_type IN (
                    'top_platform',
                    'revenue_drop',
                    'inactive_platform',
                    'best_day',
                    'first_sale'
                  )),

  -- Plain English message shown to vendor
  -- Written by the rule engine to be simple and actionable
  message         text NOT NULL,

  -- The data behind the insight — stored so we can show
  -- supporting numbers alongside the message
  -- e.g. { platform: "instagram", revenue: 45000, percentage: 67 }
  data_snapshot   jsonb,

  -- Which time window this insight covers
  period          text CHECK (period IN ('daily', 'weekly', 'monthly')),

  -- Read state for notification badge in dashboard
  is_read         boolean NOT NULL DEFAULT false,

  generated_at    timestamptz NOT NULL DEFAULT now()
);

-- Latest unread insights per vendor — used for notification badge
CREATE INDEX IF NOT EXISTS idx_insights_vendor_unread
  ON insights(vendor_id, is_read, generated_at DESC);

-- Prevent duplicate insight of same type for same period
-- (insight engine checks this before inserting)
CREATE INDEX IF NOT EXISTS idx_insights_vendor_type
  ON insights(vendor_id, insight_type, generated_at DESC);

SELECT 'webhook_logs and insights tables created' AS status;
